<template>
    <text @click="_click($event)" :style="{color: color, fontSize: size, 'font-family': 'iconfont'}">{{getFontName}}</text>
</template>

<script>
    var he = require("he");
    var iconItems = {
        "appreciate": "&#xe644;",
        "appreciatefill": "&#xe6e3",
        "check": "&#xe645;",
        "roundcheckfill": "&#xe656;",
        "roundcheck": "&#xe657;",
        "close": "&#xe646;",
        "roundclosefill": "&#xe658;",
        "roundclose": "&#xe659;",
        "delete": "&#xe6b4;",
        "deletefill": "&#xe6a6;",
        "add": "&#xe6da;",
        "roundadd": "&#xe6d9",
        "edit": "&#xe649;",
        "emoji": "&#xe64a;",
        "favorfill": "&#xe64b;",
        "favor": "&#xe64c;",
        "loadding": "&#xe64f;",
        "locationfill": "&#xe650;",
        "location": "&#xe651;",
        "phone": "&#xe652;",
        "roundrightfill": "&#xe65a;",
        "roundright": "&#xe65b;",
        "search": "&#xe65c;",
        "searchlist": "&#xe6fe",
        "time": "&#xe65f;",
        "timefill": "&#xe65e;",
        "taxi": "&#xe65d;",
        "unfold": "&#xe661;",
        "fold": "&#xe6de;",
        "warnfill": "&#xe662;",
        "warn": "&#xe663;",
        "camerafill": "&#xe664;",
        "camera": "&#xe665;",
        "commentfill": "&#xe666;",
        "comment": "&#xe667;",
        "likefill": "&#xe668;",
        "like": "&#xe669;",
        "notificationfill": "&#xe66a;",
        "notification": "&#xe66b;",
        "order": "&#xe66c;",
        "samefill": "&#xe66d;",
        "same": "&#xe66e;",
        "deliver": "&#xe671;",
        "evaluate": "&#xe672;",
        "pay": "&#xe673;",
        "send": "&#xe675;",
        "shop": "&#xe676;",
        "shopfill": "&#xe697;",
        "ticket": "&#xe677;",
        "left": "&#xe679;",
        "right": "&#xe6a3;",
        "cascades": "&#xe67c;",
        "discover": "&#xe67e;",
        "discoverfill": "&#xe6ba",
        "list": "&#xe682;",
        "more": "&#xe684;",
        "moreandroid": "&#xe6a5;",
        "myfill": "&#xe685;",
        "my": "&#xe686;",
        "scan": "&#xe689;",
        "settings": "&#xe68a;",
        "questionfill": "&#xe690;",
        "question": "&#xe691;",
        "form": "&#xe699;",
        "pic": "&#xe69b;",
        "picfill": "&#xe72c;",
        "filter": "&#xe69c;",
        "footprint": "&#xe69d;",
        "top": "&#xe69e;",
        "down": "&#xe703;",
        "pulldown": "&#xe69f;",
        "pullup": "&#xe6a0;",
        "refresh": "&#xe6a4;",
        "refund": "&#xe6ac;",
        "cart": "&#xe6af;",
        "cartfill": "&#xe6b9;",
        "qrcode": "&#xe6b0;",
        "remind": "&#xe6b2;",
        "profile": "&#xe6b7;",
        "profilefill": "&#xe77a;",
        "homefill": "&#xe6bb;",
        "home": "&#xe6b8;",
        "messagefill": "&#xe779;",
        "message": "&#xe6bc;",
        "addressbook": "&#xe6bd;",
        "link": "&#xe6bf;",
        "lock": "&#xe6c0;",
        "unlock": "&#xe6c2;",
        "vip": "&#xe6c3;",
        "vipcard": "&#xe6ee;",
        "activity": "&#xe6c5;",
        "activityfill": "&#xe775;",
        "friendaddfill": "&#xe6c9;",
        "friendadd": "&#xe6ca;",
        "friendfamous": "&#xe6cb;",
        "friend": "&#xe6cc;",
        "friendfill": "&#xe726;",
        "goods": "&#xe6cd;",
        "goodsfill": "&#xe778;",
        "selection": "&#xe6ce;",
        "selectionfill": "&#xe6e1;",
        "explore": "&#xe6d2;",
        "explorefill": "&#xe6dd;",
        "present": "&#xe6d3;",
        "presentfill": "&#xe732;",
        "squarecheckfill": "&#xe6d4;",
        "square": "&#xe6d5;",
        "squarecheck": "&#xe6d6;",
        "round": "&#xe6d7;",
        "roundfill": "&#xe6d8",
        "notificationforbidfill": "&#xe6db;",
        "game": "&#xe6df;",
        "redpacket": "&#xe6e0;",
        "similar": "&#xe6e2;",
        "infofill": "&#xe6e4;",
        "info": "&#xe6e5;",
        "forwardfill": "&#xe6ea;",
        "forward": "&#xe6eb;",
        "rechargefill": "&#xe6ec;",
        "recharge": "&#xe6ed;",
        "voice": "&#xe6ef;",
        "voicefill": "&#xe6f0;",
        "friendfavor": "&#xe6f1;",
        "wifi": "&#xe6f2;",
        "share": "&#xe6f3;",
        "wefill": "&#xe6f4;",
        "we": "&#xe6f5;",
        "lightauto": "&#xe6f6;",
        "lightforbid": "&#xe6f7;",
        "lightfill": "&#xe6f8;",
        "light": "&#xe6fa;",
        "camerarotate": "&#xe6f9;",
        "barcode": "&#xe6fb;",
        "flashlightclose": "&#xe6fc;",
        "flashlightopen": "&#xe6fd;",
        "service": "&#xe6ff;",
        "servicefill": "&#xe737;",
        "sort": "&#xe700;",
        "mobile": "&#xe704;",
        "mobilefill": "&#xe705;",
        "copy": "&#xe706;",
        "countdownfill": "&#xe707;",
        "countdown": "&#xe708;",
        "noticefill": "&#xe709;",
        "notice": "&#xe70a;",
        "upstagefill": "&#xe70e;",
        "upstage": "&#xe70f;",
        "choicenessfill": "&#xe714;",
        "choiceness": "&#xe715;",
        "clothesfill": "&#xe716;",
        "clothes": "&#xe717;",
        "creativefill": "&#xe718;",
        "creative": "&#xe719;",
        "female": "&#xe71a;",
        "male": "&#xe71c;",
        "keyboard": "&#xe71b;",
        "pullleft": "&#xe71f;",
        "pullright": "&#xe720;",
        "rankfill": "&#xe721;",
        "rank": "&#xe722;",
        "bad": "&#xe723;",
        "cameraadd": "&#xe724;",
        "cameraaddfill": "&#xe727;",
        "focus": "&#xe725;",
        "apps": "&#xe729;",
        "paintfill": "&#xe72a;",
        "paint": "&#xe72b;",
        "refresharrow": "&#xe72d;",
        "markfill": "&#xe730;",
        "mark": "&#xe731;",
        "repeal": "&#xe733;",
        "album": "&#xe734;",
        "peoplefill": "&#xe735;",
        "people": "&#xe736;",
        "repair": "&#xe738;",
        "repairfill": "&#xe73a;",
        "file": "&#xe739;",
        "taoxiaopu": "&#xe73b;",
        "attentionfill": "&#xe73c;",
        "attention": "&#xe73d;",
        "commandfill": "&#xe73e;",
        "command": "&#xe73f;",
        "communityfill": "&#xe740;",
        "community": "&#xe741;",
        "read": "&#xe743;",
        "calendar": "&#xe74a;",
        "cut": "&#xe74b;",
        "magic": "&#xe74c;",
        "backwardfill": "&#xe74d;",
        "forwardfill1": "&#xe74e;",
        "stop": "&#xe750;",
        "tagfill": "&#xe751;",
        "tag": "&#xe752;",
        "group": "&#xe753;",
        "move": "&#xe754;",
        "all": "&#xe755;",
        "backdelete": "&#xe756;",
        "hotfill": "&#xe757;",
        "hot": "&#xe758;",
        "post": "&#xe759;",
        "radiobox": "&#xe75b;",
        "radioboxfill": "&#xe763;",
        "rounddown": "&#xe75c;",
        "upload": "&#xe75d;",
        "videofill": "&#xe75e;",
        "video": "&#xe75f;",
        "writefill": "&#xe760;",
        "write": "&#xe761;",
        "punch": "&#xe764;",
        "shake": "&#xe765;",
        "safe": "&#xe769;",
        "crownfill": "&#xe776;",
        "crown": "&#xe777;",
        "sound": "&#xe77b;",
        "sponsorfill": "&#xe77c;",
        "weunblock": "&#xe780;",
        "weblock": "&#xe77f;",
        "upblock": "&#xe77e;",
        "sponsor": "&#xe77d;",
        "babyfill": "&#xe710;",
        "baby": "&#xe711;",
        "add1": "&#xe767;",
        "move1": "&#xe768;",
        "user": "&#xe736;",
        "msg": "&#xe779;",
        "erweima": "&#xe6b0",
        "radio": "&#xe6d7;",
        "radio-on": "&#xe763;",
        "checkbox-on": "&#xe656;",
        "menu": "&#xe700;",
        "back": "&#xe679;",
        "go": "&#xe6a3;",
        "book": "&#xe742;",
        "success": "&#xe657;",
        "star": "&#xe64c;",
        "liwu": "&#xe6d3",
        "jiantou": "&#xe6de",
        "hongqi": "&#xe775",

    }
    module.exports = {
        beforeCreate () {
            //ttf地址可以是本地/src/font/xx.ttf
            //也可以是远程字体文件
            var bundleUrl = weex.config.bundleUrl;
            var url = bundleUrl.split('/').slice(0, -1).join('/');
            url += '/font/iconfont.ttf';

            var domModule = weex.requireModule("dom");
            domModule.addRule('fontFace', {
                'fontFamily': 'iconfont',
                'src': "url('" + url + "')"
            });
        },
        props: {
            name: {
                type: String
            },
            color: {
                type: String,
                default: '#9ea7b4'
            },
            size: {
                type: String,
                default: '40px'
            }
        },
        computed: {
            getFontName() {
                if(this.name.startsWith("icon")){
                    this.name = this.name.split('-')[1];
                }
                return he.decode(iconItems[this.name]);
            }
        },
        methods: {
            _click($event) {
                this.$emit("click", $event);
            }
        }
    }
</script>